# Generated by Django 4.0.2 on 2022-02-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_rename_post_comments_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post_id',
            new_name='post',
        ),
    ]
